config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'
  resources :products, except: [:index]

  get 'search', to: "search#index"

  get 'checkout/success'
  get 'checkout/cancel'
  post 'checkout/session', to: 'checkout#checkout_session'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products_categories
	has_many :products, through: :products_categories

	validates :name, presence: true
	validates :desc, presence: true
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :product

  validates :name, presence: true, length: { maximum: 50 }
  validates :desc, presence: true, length: { maximum: 300 }
  validates :discount_percent, presence: true, numericality: {
    greater_than_or_equal_to: 5, less_than_or_equal_to: 75
  }

  def active?
    self.active
  end
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :products_categories
	has_one :discount
	has_one :price
	
	validates :name, presence: true, length: { maximum: 100 }
	validates :sku, presence: true, length: { maximum: 30 }, uniqueness: true
	validates :desc, presence: true, length: { maximum: 500 }
  validates :price, presence: true, numericality: {
		greater_than_or_equal_to: 0.1
  }

	def has_discount?
		Discount.find_by(product: self).active?
	end
end

app/models/products_category.rb
class ProductsCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def checkout_session
    session = Stripe::Checkout::Session.create({
      line_items: [{quantity: params[:quantity], price: params[:price]}],
      mode: 'payment',
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
    })

    redirect_to session.url, status: 303, allow_other_host: true
  end

  def success
  end

  def cancel
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :define_product, except: [:new, :create]

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    if @product.save
      create_product @product
      redirect_to product_path(@product) # add notice
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update product_params
      redirect_to product_path(@product) # add notice
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path # add notice
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :sku, :desc, :price)
  end

  def define_product
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, status: :not_found # add alert
    end
  end

  def create_product product
    stripe_product = Stripe::Product.create(
      {
        name: product.name,
        description: product.desc,
        url: product_url(product.id)
        # add images
      }
    )
    create_price(product, stripe_product)
  end

  def create_price(product, stripe_product)
    price = Stripe::Price.create(
      {
        unit_amount: real_to_centavos(product.price),
        currency: 'brl',
        product: stripe_product.id
      }
    )
    Price.create!(product: product, stripe_price_id: price.id)
  end

  def real_to_centavos price
    (price * 100).to_i
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    query = Product.ransack(name_cont: params[:q])
    @results = query.result
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/checkout/cancel.html.erb
<h1>Checkout#cancel</h1>
<p>Find me in app/views/checkout/cancel.html.erb</p>

app/views/checkout/success.html.erb
<h1>Checkout#success</h1>
<p>Find me in app/views/checkout/success.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= form_with url: search_path, method: :get do |f| %>
      <%= f.search_field :q %>
    <% end %>

    <%= link_to "new product", new_product_path %>
    <main id="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/new.html.erb
<%= form_with model: @product, url: products_path do |form| %>
	<%= form.label "name" %>
	<%= form.text_field "name" %>

	<%= form.label "sku" %>
	<%= form.text_field "sku" %>

	<%= form.label "price" %>
	<%= form.number_field "price" %>

	<%= form.label "desc" %>
	<%= form.text_area "desc" %>

	<%= form.submit %>
<% end %>

<% @product.errors.messages.each do |message| %>
  <%= message %>
<% end %>

app/views/products/show.html.erb
<%= @product.name %>
<%= @product.price %>
<%= @product.sku %>
<%= @product.desc %>

<%= form_with url: checkout_session_path, data: { turbo: false } do |form| %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity %>

  <%= form.hidden_field :price, value: @product.price.stripe_price_id %>

  <%= form.submit "Pay" %>
<% end %>

app/views/search/index.html.erb
<%= "Not exist" if @results.empty? %>
<% @results.each do |product| %>
	<%= link_to product.name, product_path(product) %>
<% end %>

app/views/search/index.turbo_stream.erb
<%= turbo_stream.replace "main" do %>
	<main id="main">
		<%= "Not exist" if @results.empty? %>
		<% @results.each do |product| %>
			<%= link_to product.name, product_path(product) %>
		<% end %>
	</main>
<% end %>